core/blog/api/v1/urls.py
from django.urls import path, include
from . import view
from django.views.generic.base import RedirectView
from rest_framework.routers import DefaultRouter

app_name = "api-v1"

router = DefaultRouter()
router.register("post", view.PostViewset, basename="post")

urlpatterns = [
    # path('post/' , view.PostList.as_view() , name='post-list'),
    # path('post/<int:pk>/' , view.PostDetailView.as_view() , name='post-detail'),
    # path('post/', view.PostViewset.as_view({'get':'list' , 'post':'create'}), name = 'post-list'),
    # path('post/<int:pk>/' , view.PostViewset.as_view({'get':'retrieve' , 'put':'update' ,'patch' :'partial_update' ,'delete':'destroy'}), name = 'post-detail'),
    path("", include(router.urls))
]

core/blog/urls.py
from django.urls import path, include
from .views import *
from django.views.generic.base import RedirectView

app_name = "blog"

urlpatterns = [
    path("cbv", IndexView.as_view(), name="cbv"),
    path("go-to-cbv/", RedirectWeb.as_view(), name="go-to-cbv"),
    path("post/", BlogPost.as_view(), name="post"),
    path("post-api",PostApiTemplateView.as_view(), name='post-api' ),
    path("post/<int:pk>", PostDetailView.as_view(), name="post-detail"),
    path("post/contact", ContactPost.as_view(), name="post-contact"),
    path("post/create", PostCreateView.as_view(), name="create-post"),
    path(
        "post/<int:pk>/update", PostUpdateView.as_view(), name="post-update"
    ),
    path(
        "post/<int:pk>/delete", PostDeleteView.as_view(), name="post-delete"
    ),
    path("api/v1/", include("blog.api.v1.urls")),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    path("accounts/", include("accounts.urls")),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]


# only use media and static in development
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

core/blog/models.py
from django.db import models

from accounts.models import Profile


# Create your models here.
class Post(models.Model):
    auther = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    status = models.BooleanField(default=True)
    category = models.ForeignKey(
        "Category", on_delete=models.SET_NULL, null=True
    )
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField()

    def __str__(self):
        return self.title

    def get_snippet(self):
        return self.content[0:5]


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

core/blog/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

core/blog/views.py
from django.shortcuts import render
from django.views.generic import (
    TemplateView,
    RedirectView,
    ListView,
    FormView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.views.generic.detail import DetailView
from .forms import ContactForm
from .models import Post
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.


class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["name"] = "hamid"
        context["post"] = Post.objects.all()
        return context


class RedirectWeb(RedirectView):
    pattern_name = "blog:cbv"


class BlogPost(LoginRequiredMixin, ListView):
    context_object_name = "posts"
    paginate_by = 2

    def get_queryset(self):
        posts = Post.objects.all()
        return posts


class PostDetailView(DetailView):
    model = Post


class ContactPost(FormView):
    template_name = "contact.html"
    form_class = ContactForm
    success_url = None

    def get_success_url(self):
        return redirect("blog:post")


class PostCreateView(CreateView):
    model = Post
    fields = ["title", "status", "category", "content", "published_date"]
    success_url = "/blog/post/"

    def form_valid(self, form):
        form.instance.auther = self.request.user
        return super().form_valid(form)


class PostUpdateView(UpdateView):
    model = Post
    fields = ["title", "status", "category", "content", "published_date"]
    success_url = "/blog/post/"


class PostDeleteView(DeleteView):
    model = Post
    success_url = "/blog/post/"

class PostApiTemplateView(TemplateView):
    template_name='blog/post-api.html'

core/templates/blog/post-api.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>agsf</title>
</head>
<body>
    
</body>
</html>

core/templates/blog/post_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

core/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{object.title}}</h1>
    <p>{{object.content}}</p>
</body>
</html>

core/templates/blog/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
</body>
</html>

core/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>blog post</title>
</head>
<body>
    <h1>this is blog post</h1>
    {% for post in posts %}
    <div>
       <a href="{% url 'blog:post-detail' pk=post.id %}"><h2>{{post.title}}</h2></a>
    </div>
  {% endfor %}
  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</body>
</html>